# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'super_marche.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SuperMarche(object):
    def setupUi(self, SuperMarche):
        SuperMarche.setObjectName("SuperMarche")
        SuperMarche.resize(833, 633)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/logo-tranparent.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SuperMarche.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(SuperMarche)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 93, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(self.page)
        self.label.setMaximumSize(QtCore.QSize(75, 75))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/man.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setStyleSheet("font: 75 14pt \"Ubuntu Mono\";")
        self.label_2.setScaledContents(True)
        self.label_2.setIndent(3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.lineEdit_nom_utilisateur = QtWidgets.QLineEdit(self.page)
        self.lineEdit_nom_utilisateur.setMinimumSize(QtCore.QSize(350, 40))
        self.lineEdit_nom_utilisateur.setMaximumSize(QtCore.QSize(350, 40))
        self.lineEdit_nom_utilisateur.setStyleSheet("border-radius : 9px;\n"
"background-color : white;\n"
"padding-left : 9px;\n"
"font: 25 12pt \"Ubuntu Light\";")
        self.lineEdit_nom_utilisateur.setObjectName("lineEdit_nom_utilisateur")
        self.verticalLayout_2.addWidget(self.lineEdit_nom_utilisateur)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setStyleSheet("font: 75 14pt \"Ubuntu Mono\";")
        self.label_3.setScaledContents(True)
        self.label_3.setIndent(3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_mot_de_passe = QtWidgets.QLineEdit(self.page)
        self.lineEdit_mot_de_passe.setMinimumSize(QtCore.QSize(350, 40))
        self.lineEdit_mot_de_passe.setMaximumSize(QtCore.QSize(350, 40))
        self.lineEdit_mot_de_passe.setStyleSheet("border-radius : 9px;\n"
"background-color : white;\n"
"padding-left : 9px;\n"
"font: 25 12pt \"Ubuntu Light\";")
        self.lineEdit_mot_de_passe.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_mot_de_passe.setObjectName("lineEdit_mot_de_passe")
        self.horizontalLayout_5.addWidget(self.lineEdit_mot_de_passe)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.label_visibilite_pass = QtWidgets.QLabel(self.page)
        self.label_visibilite_pass.setMaximumSize(QtCore.QSize(25, 40))
        self.label_visibilite_pass.setText("")
        self.label_visibilite_pass.setPixmap(QtGui.QPixmap("images/interface.png"))
        self.label_visibilite_pass.setScaledContents(True)
        self.label_visibilite_pass.setObjectName("label_visibilite_pass")
        self.horizontalLayout_5.addWidget(self.label_visibilite_pass)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.label_information_connexion = QtWidgets.QLabel(self.page)
        self.label_information_connexion.setMinimumSize(QtCore.QSize(400, 30))
        self.label_information_connexion.setMaximumSize(QtCore.QSize(200, 30))
        self.label_information_connexion.setStyleSheet("")
        self.label_information_connexion.setText("")
        self.label_information_connexion.setAlignment(QtCore.Qt.AlignCenter)
        self.label_information_connexion.setObjectName("label_information_connexion")
        self.verticalLayout_3.addWidget(self.label_information_connexion)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.bouton_connexion = QtWidgets.QPushButton(self.page)
        self.bouton_connexion.setMinimumSize(QtCore.QSize(100, 50))
        self.bouton_connexion.setMaximumSize(QtCore.QSize(250, 50))
        self.bouton_connexion.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bouton_connexion.setStyleSheet("font: 75 14pt \"Ubuntu Mono\";\n"
"border-radius : 9px;\n"
"background-color : black;\n"
"color : white;\n"
"")
        self.bouton_connexion.setObjectName("bouton_connexion")
        self.horizontalLayout_4.addWidget(self.bouton_connexion)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 92, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem11, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem12)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_14 = QtWidgets.QLabel(self.page_2)
        self.label_14.setMinimumSize(QtCore.QSize(50, 40))
        self.label_14.setMaximumSize(QtCore.QSize(40, 40))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("images/logo-tranparent.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_16.addWidget(self.label_14)
        self.label_13 = QtWidgets.QLabel(self.page_2)
        self.label_13.setMinimumSize(QtCore.QSize(0, 50))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_13.setStyleSheet("font: 19pt \"Ubuntu Mono\";\n"
"")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_16.addWidget(self.label_13)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_16)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem13)
        self.gridLayout_6.addLayout(self.horizontalLayout_17, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.bouton_liste_article = QtWidgets.QPushButton(self.page_2)
        self.bouton_liste_article.setMinimumSize(QtCore.QSize(200, 50))
        self.bouton_liste_article.setMaximumSize(QtCore.QSize(200, 30))
        self.bouton_liste_article.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bouton_liste_article.setStyleSheet("font: 75 13pt \"Ubuntu Mono\";\n"
"border-radius : 10px;\n"
"background-color : green;")
        self.bouton_liste_article.setIconSize(QtCore.QSize(30, 16))
        self.bouton_liste_article.setObjectName("bouton_liste_article")
        self.verticalLayout_4.addWidget(self.bouton_liste_article)
        self.bouton_ajouter_article = QtWidgets.QPushButton(self.page_2)
        self.bouton_ajouter_article.setMinimumSize(QtCore.QSize(200, 50))
        self.bouton_ajouter_article.setMaximumSize(QtCore.QSize(200, 30))
        self.bouton_ajouter_article.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bouton_ajouter_article.setStyleSheet("font: 75 13pt \"Ubuntu Mono\";\n"
"border-radius : 10px;\n"
"background-color : green;")
        self.bouton_ajouter_article.setIconSize(QtCore.QSize(30, 16))
        self.bouton_ajouter_article.setObjectName("bouton_ajouter_article")
        self.verticalLayout_4.addWidget(self.bouton_ajouter_article)
        self.bouton_modifier_article = QtWidgets.QPushButton(self.page_2)
        self.bouton_modifier_article.setMinimumSize(QtCore.QSize(200, 50))
        self.bouton_modifier_article.setMaximumSize(QtCore.QSize(200, 30))
        self.bouton_modifier_article.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bouton_modifier_article.setStyleSheet("font: 75 12pt \"Ubuntu Mono\";\n"
"border-radius : 10px;\n"
"background-color : green;")
        self.bouton_modifier_article.setIconSize(QtCore.QSize(30, 16))
        self.bouton_modifier_article.setObjectName("bouton_modifier_article")
        self.verticalLayout_4.addWidget(self.bouton_modifier_article)
        self.bouton_supprimer_article = QtWidgets.QPushButton(self.page_2)
        self.bouton_supprimer_article.setMinimumSize(QtCore.QSize(200, 50))
        self.bouton_supprimer_article.setMaximumSize(QtCore.QSize(200, 30))
        self.bouton_supprimer_article.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bouton_supprimer_article.setStyleSheet("font: 75 13pt \"Ubuntu Mono\";\n"
"border-radius : 10px;\n"
"background-color : green;")
        self.bouton_supprimer_article.setIconSize(QtCore.QSize(30, 16))
        self.bouton_supprimer_article.setObjectName("bouton_supprimer_article")
        self.verticalLayout_4.addWidget(self.bouton_supprimer_article)
        self.bouton_liste_vente = QtWidgets.QPushButton(self.page_2)
        self.bouton_liste_vente.setMinimumSize(QtCore.QSize(200, 50))
        self.bouton_liste_vente.setMaximumSize(QtCore.QSize(200, 30))
        self.bouton_liste_vente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bouton_liste_vente.setStyleSheet("font: 75 13pt \"Ubuntu Mono\";\n"
"border-radius : 10px;\n"
"background-color : green;")
        self.bouton_liste_vente.setIconSize(QtCore.QSize(30, 16))
        self.bouton_liste_vente.setObjectName("bouton_liste_vente")
        self.verticalLayout_4.addWidget(self.bouton_liste_vente)
        self.bouton_achat_vente = QtWidgets.QPushButton(self.page_2)
        self.bouton_achat_vente.setMinimumSize(QtCore.QSize(200, 50))
        self.bouton_achat_vente.setMaximumSize(QtCore.QSize(200, 30))
        self.bouton_achat_vente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bouton_achat_vente.setStyleSheet("font: 75 13pt \"Ubuntu Mono\";\n"
"border-radius : 10px;\n"
"background-color : green;")
        self.bouton_achat_vente.setIconSize(QtCore.QSize(30, 16))
        self.bouton_achat_vente.setObjectName("bouton_achat_vente")
        self.verticalLayout_4.addWidget(self.bouton_achat_vente)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page_2)
        self.stackedWidget_2.setStyleSheet("")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.stackedWidget_2.addWidget(self.page_7)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem14)
        self.label_8 = QtWidgets.QLabel(self.page_3)
        self.label_8.setMinimumSize(QtCore.QSize(200, 50))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_8.setStyleSheet("font: 75 16pt \"Ubuntu Mono\";\n"
"text-decoration: underline;")
        self.label_8.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_12.addWidget(self.label_8)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem15)
        self.gridLayout_4.addLayout(self.horizontalLayout_12, 0, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(17, 49, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem16, 0, 1, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem17 = QtWidgets.QSpacerItem(136, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem17)
        self.tableWidget = QtWidgets.QTableWidget(self.page_3)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 400))
        self.tableWidget.setStyleSheet("font: 14pt \"Ubuntu Mono\";")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout_20.addWidget(self.tableWidget)
        spacerItem18 = QtWidgets.QSpacerItem(135, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem18)
        self.gridLayout_4.addLayout(self.horizontalLayout_20, 1, 0, 1, 3)
        spacerItem19 = QtWidgets.QSpacerItem(17, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem19, 2, 1, 1, 1)
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem20 = QtWidgets.QSpacerItem(20, 57, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem20, 0, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem21)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem22)
        self.label_7 = QtWidgets.QLabel(self.page_4)
        self.label_7.setMinimumSize(QtCore.QSize(300, 50))
        self.label_7.setStyleSheet("font: 15pt \"Ubuntu Mono\";\n"
"background-color : white;\n"
"border-radius : 9px;\n"
"border : 2px solid black;\n"
"box-shadow : 2px 3px solid black;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem23)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        spacerItem24 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem24)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem25)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.page_4)
        self.label_5.setStyleSheet("font: 12pt \"Ubuntu Mono\";\n"
"padding-left : 3px;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.lineEdit_nom_article_ajouter = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_nom_article_ajouter.setMinimumSize(QtCore.QSize(300, 40))
        self.lineEdit_nom_article_ajouter.setMaximumSize(QtCore.QSize(300, 40))
        self.lineEdit_nom_article_ajouter.setStyleSheet("border-radius : 9px;\n"
"font: 57 12pt \"Ubuntu Light\";\n"
"background-color : white;\n"
"padding-left : 3px;")
        self.lineEdit_nom_article_ajouter.setObjectName("lineEdit_nom_article_ajouter")
        self.verticalLayout_5.addWidget(self.lineEdit_nom_article_ajouter)
        self.label_6 = QtWidgets.QLabel(self.page_4)
        self.label_6.setStyleSheet("font: 12pt \"Ubuntu Mono\";\n"
"padding-left : 3px;")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.spinBox_quantite_article_ajouter = QtWidgets.QSpinBox(self.page_4)
        self.spinBox_quantite_article_ajouter.setMaximumSize(QtCore.QSize(100, 30))
        self.spinBox_quantite_article_ajouter.setMaximum(999999999)
        self.spinBox_quantite_article_ajouter.setObjectName("spinBox_quantite_article_ajouter")
        self.verticalLayout_5.addWidget(self.spinBox_quantite_article_ajouter)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem26)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem27)
        self.bouton_valider_ajouter_article = QtWidgets.QPushButton(self.page_4)
        self.bouton_valider_ajouter_article.setMinimumSize(QtCore.QSize(150, 45))
        self.bouton_valider_ajouter_article.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bouton_valider_ajouter_article.setStyleSheet("font: 75 13pt \"Ubuntu Mono\";\n"
"border-radius : 10px;\n"
"background-color : black;\n"
"color:white")
        self.bouton_valider_ajouter_article.setObjectName("bouton_valider_ajouter_article")
        self.horizontalLayout_8.addWidget(self.bouton_valider_ajouter_article)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem28)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.label_info_ajouter_article = QtWidgets.QLabel(self.page_4)
        self.label_info_ajouter_article.setMinimumSize(QtCore.QSize(200, 30))
        self.label_info_ajouter_article.setText("")
        self.label_info_ajouter_article.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_ajouter_article.setObjectName("label_info_ajouter_article")
        self.verticalLayout_7.addWidget(self.label_info_ajouter_article)
        self.horizontalLayout_9.addLayout(self.verticalLayout_7)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem29)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11.addLayout(self.verticalLayout_8)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem30)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 1, 0, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(20, 56, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem31, 2, 0, 1, 1)
        self.stackedWidget_2.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem32 = QtWidgets.QSpacerItem(132, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem32, 0, 0, 1, 1)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        spacerItem33 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem33)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_9 = QtWidgets.QLabel(self.page_5)
        self.label_9.setMinimumSize(QtCore.QSize(120, 20))
        self.label_9.setStyleSheet("font: 75 12pt \"Ubuntu Mono\";")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_11.addWidget(self.label_9)
        self.lineEdit_nom_article_modifier = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_nom_article_modifier.setMinimumSize(QtCore.QSize(300, 40))
        self.lineEdit_nom_article_modifier.setMaximumSize(QtCore.QSize(300, 40))
        self.lineEdit_nom_article_modifier.setStyleSheet("font: 75 12pt \"Ubuntu Mono\";\n"
"border-radius : 2px;\n"
"padding-left : 2px;")
        self.lineEdit_nom_article_modifier.setObjectName("lineEdit_nom_article_modifier")
        self.verticalLayout_11.addWidget(self.lineEdit_nom_article_modifier)
        self.label_10 = QtWidgets.QLabel(self.page_5)
        self.label_10.setMinimumSize(QtCore.QSize(120, 20))
        self.label_10.setStyleSheet("font: 75 12pt \"Ubuntu Mono\";")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_11.addWidget(self.label_10)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.spinBox_quantite_modifier = QtWidgets.QSpinBox(self.page_5)
        self.spinBox_quantite_modifier.setMaximum(999999999)
        self.spinBox_quantite_modifier.setObjectName("spinBox_quantite_modifier")
        self.horizontalLayout_14.addWidget(self.spinBox_quantite_modifier)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem34)
        self.verticalLayout_11.addLayout(self.horizontalLayout_14)
        self.label_11 = QtWidgets.QLabel(self.page_5)
        self.label_11.setMinimumSize(QtCore.QSize(120, 20))
        self.label_11.setStyleSheet("font: 75 12pt \"Ubuntu Mono\";")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_11.addWidget(self.label_11)
        self.lineEdit_nouveau_nom_article_modifier = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_nouveau_nom_article_modifier.setMinimumSize(QtCore.QSize(300, 40))
        self.lineEdit_nouveau_nom_article_modifier.setMaximumSize(QtCore.QSize(300, 40))
        self.lineEdit_nouveau_nom_article_modifier.setStyleSheet("font: 75 12pt \"Ubuntu Mono\";\n"
"border-radius : 2px;\n"
"padding-left : 2px;")
        self.lineEdit_nouveau_nom_article_modifier.setObjectName("lineEdit_nouveau_nom_article_modifier")
        self.verticalLayout_11.addWidget(self.lineEdit_nouveau_nom_article_modifier)
        self.label_12 = QtWidgets.QLabel(self.page_5)
        self.label_12.setMinimumSize(QtCore.QSize(120, 20))
        self.label_12.setStyleSheet("font: 75 12pt \"Ubuntu Mono\";")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_11.addWidget(self.label_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.spinBox_nouvelle_quantite_modifier = QtWidgets.QSpinBox(self.page_5)
        self.spinBox_nouvelle_quantite_modifier.setMaximum(999999999)
        self.spinBox_nouvelle_quantite_modifier.setObjectName("spinBox_nouvelle_quantite_modifier")
        self.horizontalLayout_13.addWidget(self.spinBox_nouvelle_quantite_modifier)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem35)
        self.verticalLayout_11.addLayout(self.horizontalLayout_13)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem36)
        self.bouton_valider_modifier_article = QtWidgets.QPushButton(self.page_5)
        self.bouton_valider_modifier_article.setMinimumSize(QtCore.QSize(100, 40))
        self.bouton_valider_modifier_article.setMaximumSize(QtCore.QSize(100, 40))
        self.bouton_valider_modifier_article.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bouton_valider_modifier_article.setStyleSheet("font: 75 12pt \"Ubuntu Mono\";")
        self.bouton_valider_modifier_article.setObjectName("bouton_valider_modifier_article")
        self.horizontalLayout_15.addWidget(self.bouton_valider_modifier_article)
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem37)
        self.verticalLayout_12.addLayout(self.horizontalLayout_15)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        spacerItem38 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem38)
        self.gridLayout_5.addLayout(self.verticalLayout_13, 0, 1, 1, 1)
        spacerItem39 = QtWidgets.QSpacerItem(131, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem39, 0, 2, 1, 1)
        self.stackedWidget_2.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem40)
        self.label_15 = QtWidgets.QLabel(self.page_6)
        self.label_15.setMinimumSize(QtCore.QSize(300, 50))
        self.label_15.setStyleSheet("font: 15pt \"Ubuntu Mono\";\n"
"background-color : white;\n"
"border-radius : 9px;\n"
"border : 2px solid black;\n"
"box-shadow : 2px 3px solid black;")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_19.addWidget(self.label_15)
        spacerItem41 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem41)
        self.gridLayout_7.addLayout(self.horizontalLayout_19, 1, 0, 1, 2)
        spacerItem42 = QtWidgets.QSpacerItem(20, 64, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem42, 0, 1, 1, 1)
        spacerItem43 = QtWidgets.QSpacerItem(20, 64, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem43, 4, 0, 1, 1)
        self.label_info_ajouter_article_2 = QtWidgets.QLabel(self.page_6)
        self.label_info_ajouter_article_2.setMinimumSize(QtCore.QSize(200, 30))
        self.label_info_ajouter_article_2.setText("")
        self.label_info_ajouter_article_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_ajouter_article_2.setObjectName("label_info_ajouter_article_2")
        self.gridLayout_7.addWidget(self.label_info_ajouter_article_2, 5, 0, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem44 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem44)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_16 = QtWidgets.QLabel(self.page_6)
        self.label_16.setStyleSheet("font: 12pt \"Ubuntu Mono\";\n"
"padding-left : 3px;")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_14.addWidget(self.label_16)
        self.lineEdit_article_a_supprimer = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_article_a_supprimer.setMinimumSize(QtCore.QSize(300, 40))
        self.lineEdit_article_a_supprimer.setMaximumSize(QtCore.QSize(300, 40))
        self.lineEdit_article_a_supprimer.setStyleSheet("border-radius : 9px;\n"
"font: 57 12pt \"Ubuntu Light\";\n"
"background-color : white;\n"
"padding-left : 3px;")
        self.lineEdit_article_a_supprimer.setObjectName("lineEdit_article_a_supprimer")
        self.verticalLayout_14.addWidget(self.lineEdit_article_a_supprimer)
        self.verticalLayout_15.addLayout(self.verticalLayout_14)
        spacerItem45 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem45)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem46 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem46)
        self.bouton_valider_supprimer = QtWidgets.QPushButton(self.page_6)
        self.bouton_valider_supprimer.setMinimumSize(QtCore.QSize(150, 45))
        self.bouton_valider_supprimer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bouton_valider_supprimer.setStyleSheet("font: 75 13pt \"Ubuntu Mono\";\n"
"border-radius : 10px;\n"
"background-color : black;\n"
"color:white")
        self.bouton_valider_supprimer.setObjectName("bouton_valider_supprimer")
        self.horizontalLayout_21.addWidget(self.bouton_valider_supprimer)
        spacerItem47 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem47)
        self.verticalLayout_15.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_18.addLayout(self.verticalLayout_15)
        spacerItem48 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem48)
        self.gridLayout_7.addLayout(self.horizontalLayout_18, 3, 0, 1, 2)
        spacerItem49 = QtWidgets.QSpacerItem(20, 65, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem49, 2, 0, 1, 1)
        self.stackedWidget_2.addWidget(self.page_6)
        self.horizontalLayout_7.addWidget(self.stackedWidget_2)
        self.gridLayout_6.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 0, 1, 1, 1)
        SuperMarche.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SuperMarche)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 833, 30))
        self.menubar.setObjectName("menubar")
        SuperMarche.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SuperMarche)
        self.statusbar.setObjectName("statusbar")
        SuperMarche.setStatusBar(self.statusbar)

        self.retranslateUi(SuperMarche)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SuperMarche)

    def retranslateUi(self, SuperMarche):
        _translate = QtCore.QCoreApplication.translate
        SuperMarche.setWindowTitle(_translate("SuperMarche", "Super Marche"))
        self.label_2.setText(_translate("SuperMarche", "Nom d\'utilisateur"))
        self.label_3.setText(_translate("SuperMarche", "Mot de passe"))
        self.bouton_connexion.setText(_translate("SuperMarche", "Connexion"))
        self.label_13.setText(_translate("SuperMarche", "SYSTÈME DE GESTION D\'UN SUPERMARCHE"))
        self.bouton_liste_article.setText(_translate("SuperMarche", "Liste des Articles"))
        self.bouton_ajouter_article.setText(_translate("SuperMarche", "Ajouter un article"))
        self.bouton_modifier_article.setText(_translate("SuperMarche", "Mise à jour d\'un article"))
        self.bouton_supprimer_article.setText(_translate("SuperMarche", "Supprimer un article"))
        self.bouton_liste_vente.setText(_translate("SuperMarche", "Liste des ventes"))
        self.bouton_achat_vente.setText(_translate("SuperMarche", "Achats des clients"))
        self.label_8.setText(_translate("SuperMarche", "Liste des articles"))
        self.label_7.setText(_translate("SuperMarche", "Ajouter un article "))
        self.label_5.setText(_translate("SuperMarche", "Nom de l\'article"))
        self.label_6.setText(_translate("SuperMarche", "Quantité"))
        self.bouton_valider_ajouter_article.setText(_translate("SuperMarche", "Ajouter"))
        self.label_9.setText(_translate("SuperMarche", "Nom de l\'article"))
        self.label_10.setText(_translate("SuperMarche", "Quantité"))
        self.label_11.setText(_translate("SuperMarche", "Nouveau nom"))
        self.label_12.setText(_translate("SuperMarche", "Nouvelle quantité"))
        self.bouton_valider_modifier_article.setText(_translate("SuperMarche", "Modifier"))
        self.label_15.setText(_translate("SuperMarche", "Suppression d\'un article "))
        self.label_16.setText(_translate("SuperMarche", "Nom de l\'article"))
        self.bouton_valider_supprimer.setText(_translate("SuperMarche", "Supprimer"))
